[input]
Cookie = "cid=455624b540a8de6aeaa08f70e1766b3c1633915581; ComputerID=455624b540a8de6aeaa08f70e1766b3c1633915581; WafStatus=0; other_uid=Ths_iwencai_Xuangu_mmv59i1ewjjq0qjic7508zl8lo9ey3kv; ta_random_userid=cpqvgfbw57; guideState=1; user=MDpteF81OTA2NzkxMDg6Ok5vbmU6NTAwOjYwMDY3OTEwODo3LDExMTExMTExMTExLDQwOzQ0LDExLDQwOzYsMSw0MDs1LDEsNDA7MSwxMDEsNDA7MiwxLDQwOzMsMSw0MDs1LDEsNDA7OCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMSw0MDsxMDIsMSw0MDoxNjo6OjU5MDY3OTEwODoxNjUxMTk0MjgyOjo6MTYyNjg1MTI4MDo4MzQ5MTg6MDoxNzcwNmI4MjkxYjlmNjIwYWZkMGM3YWZiZmJmNWUwYjg6ZGVmYXVsdF80OjA%3D; userid=590679108; u_name=mx_590679108; escapename=mx_590679108; ticket=b82649ce47a8622cfb0825de8dc26a6e; user_status=0; utk=9da3a56591791bd8e6f8eaa5697ada91; "

[[input.reqs]]
name = "zhiwanshouban"
ques = "非ST；非新股；非创业板；非科创板；竞价非大卖单试盘；竞价实际换手率>0.3；开盘涨幅>0.01<7.5；竞价量比>7；竞价委比；今日竞价金额占昨日成交额比>3.5；未匹配金额；今日竞价金额>980万；昨日首板；昨日主力增仓占比；昨日非缩量涨停;（昨日涨停价-昨日开盘价）/昨日涨停价>1%；股本规模非大盘股；"

[[input.reqs]]
name = "lianbanxinceshi"
ques = "非st；非新股；非创业板；非科创板；竞价实际换手率>0.8；9:19分涨停；开盘涨幅>-0.1%；竞价量比>9.5；分时委比；今日竞价金额与昨日竞价金额比；今日竞价金额占昨日成交额比>8%；未匹配金额>-100万；今日开盘价/涨停价<0.97；昨日几天几板；昨日主力增仓占比<5；昨日连续涨停天数>0；昨日非炸板；（昨日涨停价-昨日开盘价）/昨日涨停价>2%；昨日成交量/10日平均成交量<3；股本规模非大盘股；"

[[input.reqs]]
name = "feibiaoxinceshi"
ques = "非st；非新股；非创业板；非科创板；竞价实际换手率>0.8；9:19分涨停；开盘涨幅>-0.1%；竞价量比>9.5；分时委比；今日竞价金额与昨日竞价金额比；今日竞价金额占昨日成交额比>8%；未匹配金额>-100万；今日开盘价/涨停价<0.97；昨日非几天几板；昨日主力增仓占比>0；昨日连续涨停天数；昨日非炸板；（昨日涨停价-昨日开盘价）/昨日涨停价>2%；昨日成交量/10日平均成交量<3；股本规模非大盘股；"

[[input.reqs]]
name = "shouban"
ques = "非st；非新股；非创业板；非竞价砸盘；竞价非大卖单试盘；竞价实际换手率>0.6%；开盘-0.1%到7.5%；竞价金额占昨日成交额>4%；竞价委比>-91；竞价量比8到79；竞价未匹配金额>-100万；今日竞价金额与昨日竞价金额比>2；今日竞价金额排序；昨日首板；昨日连续涨停天数；（昨日涨停价-昨日开盘价）/昨日涨停价>2%；昨日主力增仓占比<5；昨日非缩量；昨日成交量/10日平均成交量<3；股本规模非大盘股；昨日首次涨停时间排行；今日竞价金额>1990万；"

[input.result]
name = "jinriresult"
ques = "非ST；非新股；非创业板；非科创板；竞价非大卖单试盘；今日涨停；竞价实际换手率>0.6；开盘涨幅>0.01<7.5；竞价量比>7；今日竞价金额占昨日成交额比>3.5；未匹配金额；今日竞价金额>980万；昨日首板；昨日主力增仓占比；昨日非缩量涨停;（昨日涨停价-昨日开盘价）/昨日涨停价>1%；股本规模非大盘股；"

[input.computedata]
huanshou = [
    [2, 200, 6],
    [1.8, 2, 3],
    [1.6, 1.8, 6],
    [1.4, 1.6, 8],
    [1.2, 1.4, 5],
    [1, 1.2, 9],
    [0.8, 1, 10],
    [0.6, 0.8, 9],
    [0, 0.6, 1]
]

liangbi = [
    [100, 1000, 3],
    [90, 100, 3],
    [80, 90, 4],
    [70, 80, 4],
    [60, 70, 5],
    [50, 60, 5],
    [40, 50, 7],
    [30, 40, 7],
    [20, 30, 10],
    [10, 20, 10],
    [0, 10, 5]
]
jingzhanzuo = [
    [32, 100, 0],
    [24, 32, 3],
    [16, 24, 6],
    [8, 16, 9],
    [0, 8, 10]
]
weipipei = [
    [0.2, 1, 12],
    [0.1, 0.2, 11],
    [0.05, 0.1, 10],
    [0, 0.05, 10],
    [-0.05, 0, 9],
    [-0.1, -0.05, 4],
    [-0.2, -0.1, 2],
    [-1, -0.2, 0]
]
jingjiajine = [
    [3500, 1000000, 10],
    [2500, 3500, 10],
    [1500, 2500, 10],
    [1000, 1500, 8],
    [0, 1000, 1]
]
zhuli = [
    [30, 100, 0],
    [15, 30, 2],
    [5, 15, 8],
    [-5, 5, 10],
    [-15, -5, 9],
    [-30, -15, 7],
    [-100, -30, 3]
]