[input]
req = "非ST；非科创板；竞价涨幅0.01%到7%；今日竞价金额占昨日成交额比>3%；今日竞价成交量与昨日竞价成交量比<200；竞价实际换手率>0.3%；竞价量比排行前10；竞价量比>10；竞价开盘委比；未匹配金额>0；昨日非几天几板；昨日主力增仓占比<2；（昨日涨停价-昨日开盘价）/昨日涨停价>1%；股本规模非大盘股；"
todaystring = "20220117"
count = 10